# Generated by Django 6.0 on 2026-01-20 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditlog_company_document_documentversion_project_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('ISSUE', 'Issue'), ('CANCEL', 'Cancel'), ('DELETE', 'Delete')], max_length=20),
        ),
    ]
