# Generated by Django 6.0 on 2026-01-20 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_auditlog_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='versions', to='core.document'),
        ),
    ]
