# Generated by Django 6.0 on 2026-01-26 11:27

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_documentversion_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentversion',
            name='file',
            field=models.FileField(upload_to=core.models.document_upload_path),
        ),
    ]
