# Generated by Django 6.0 on 2026-05-09 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_documentversion_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='discipline',
            field=models.CharField(choices=[('STRUCTURAL', 'Structural'), ('CIVIL', 'Civil'), ('ARCHITECTURAL', 'Architectural'), ('MECHANICAL', 'Mechanical'), ('ELECTRICAL', 'Electrical'), ('GEOTECHNICAL', 'Geotechnical'), ('SURVEY', 'Survey'), ('ENVIRONMENTAL', 'Environmental')], max_length=20),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_type',
            field=models.CharField(choices=[('DRAWING', 'Drawing'), ('SPECIFICATION', 'Specification'), ('REPORT', 'Report'), ('CALCULATION', 'Calculation'), ('METHOD_STATEMENT', 'Method Statement'), ('INSPECTION', 'Inspection'), ('TRANSMITTAL', 'Transmittal'), ('CORRESPONDENCE', 'Correspondence')], max_length=20),
        ),
    ]
