# Generated by Django 6.0 on 2026-05-09 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_document_discipline_alter_document_doc_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('ON_HOLD', 'On Hold'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=10),
        ),
    ]
