# Generated by Django 6.0 on 2026-05-09 11:18

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_project_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentversion',
            name='file',
            field=models.FileField(upload_to=core.models.document_upload_path, validators=[core.models.validate_document_file]),
        ),
    ]
